name = "flrbin"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]



[vars]
MODE = "demo"
DEMO_CLEAR_INTERVAL = "5"

[[kv_namespaces]]
binding = "KV"
id = "flrbin"
preview_id = "f572e242ba264549bdacb3d89dc94623" #make sure to update this before deployment

[triggers]
crons = ["* * * * *"]

[assets]
directory = "./static"

